baseURL = 'https://arc-seminars.github.io/arc-seminars/'
languageCode = 'en-us'
title = 'Caltech ARC Seminars'

theme = 'rusty-typewriter'

# for github page hosting
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menus.main]]
 name = 'Seminars'
 pageRef = '/seminars'
 weight = 1

[[menus.main]]
 name = 'Tags'
 pageRef = '/tags'
 weight = 2
