baseURL = 'https://arc-seminars.github.io/'
languageCode = 'en-us'
title = 'Caltech ARC Seminars'
theme = 'rusty-typewriter'

# for github page hosting
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# for the search bar
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS", "SearchIndex"]

[params]
  basePath = "/"
  searchLimit = 20  # or whatever number you want

# for the menu bar
[[menus.main]]
 name = 'Seminars'
 pageRef = '/seminars'
 weight = 1

[[menus.main]]
 name = 'Tags'
 pageRef = '/tags'
 weight = 2
